In [1]:
import numpy as np

# Define the system
A = np.array([[1, 1], [0, 1]])  # State Transition Matrix
H = np.array([[1, 0]])         # Measurement Matrix
Q = np.array([[0.001, 0], [0, 0.001]])  # Process Noise Covariance
R = 0.1                         # Measurement Noise Covariance
P = np.eye(2)                   # Initial Estimate Covariance
x = np.array([[0], [0]])        # Initial State Estimate

# Measurements
z = np.array([1.0, 1.5, 2.0, 2.2, 3.3, 123, 123131, 1.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])  # Example measurements

# Kalman Filter Iterations
for k in range(len(z)):
    # Prediction
    x = np.dot(A, x)
    P = np.dot(A, np.dot(P, A.T)) + Q
    
    # Update
    K = np.dot(np.dot(P, H.T), np.linalg.inv(np.dot(H, np.dot(P, H.T)) + R))
    x = x + np.dot(K, (z[k] - np.dot(H, x)))
    P = np.dot((np.eye(2) - np.dot(K, H)), P)
    
    # Display the results
    print(f'Iteration {k + 1}:')
    print('State estimate:', x.T[0])
    print('Covariance:')
    print(P)


Iteration 1:
State estimate: [0.95240362 0.47596383]
Covariance:
[[0.09524036 0.04759638]
 [0.04759638 0.52503617]]
Iteration 2:
State estimate: [1.49122655 0.52620348]
Covariance:
[[0.08775214 0.07013522]
 [0.07013522 0.12441906]]
Iteration 3:
State estimate: [2.00384394 0.51872493]
Covariance:
[[0.07794645 0.04290613]
 [0.04290613 0.04194334]]
Iteration 4:
State estimate: [2.30517337 0.42948588]
Covariance:
[[0.06739507 0.02766511]
 [0.02766511 0.01946963]]
Iteration 5:
State estimate: [3.06753596 0.53905722]
Covariance:
[[0.05888072 0.01938147]
 [0.01938147 0.01133423]]
Iteration 6:
State estimate: [66.14000942 18.00399958]
Covariance:
[[0.05237594 0.01462806]
 [0.01462806 0.00784112]]
Iteration 7:
State estimate: [58530.37952708 14533.23341608]
Covariance:
[[0.04749917 0.01179651]
 [0.01179651 0.00619054]]
Iteration 8:
State estimate: [40982.32042305  7161.90503814]
Covariance:
[[0.04390931 0.01008906]
 [0.01008906 0.00537582]]
Iteration 9:
State estimate: [28243.58442764  2794.225